[package]
name = "pyforked"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.29.0", features = ["term", "socket", "uio", "fs", "poll", "signal", "ioctl"] }
signal-hook = "0.3.17"
